#SingleInstance, force
#Persistent

;process automator
out = %A_Desktop%\Script.ahk
script=#SingleInstance, force`n#Persistent`n`;Generated By GScript
Menu, tray, nodefault
Menu, tray, nostandard
Menu, tray, add, Save Script, Save
Menu, tray, add, Preview Script, Preview
Menu, tray, add,
Menu, tray, add, Reload, Reload
Menu, tray, add, Exit, Exit
return

Reload:
Reload
return

Exit:
ExitApp

Open:
Run, Notepad.exe "%out%"
return

^LButton::
CoordMode, mouse, Screen
MouseGetPos, xx, yy
CoordMode, mouse, Window
MouseGetPos, x, y,winid,contrl
WinGetTitle, win, ahk_id %winid%
menu, items, add, CANCEL THIS, handle
menu, script, add, Save This Script, save
menu, script, add, Preview Generated Code, preview
menu, items, add, Script, :script
menu, items, add,
menu, items, add, Mouse Click, handle
menu, items, add, Control Click, handle
menu, items, add, Press Buttons, handle
menu, items, add, Press Buttons Control, handle
menu, items, add, ComboBox Choose, handle
menu, items, add, ComboBox Choose Contains, handle
menu, items, add, List Choose, handle
menu, items, add, Sleep, handle
menu, items, add, WinWaitActive, handle
menu, items, add, WinWaitClose, handle
menu, items, add, WinWait, handle
menu, items, add,
menu, items, add, Run, handle
menu, items, add, Code, handle
menu, items, show
menu, items, DeleteAll
return

handle:
action := A_ThisMenuItem
if action = CANCEL THIS
	return
if action = Code
{
	InputBox, inp, Code, Type your line of code,,300, 140
	if inp =
		return
	if errorlevel
		return
	code =%inp%
}
if action = Run
{
	InputBox, inp, Run, Program to run,,300, 140
	if inp =
		return
	if errorlevel
		return
	code =Run, %inp%
}
if action = Mouse Click
{
	InputBox, inp, Mouse Click, Type "S" to use Screen coordinates(%xx%`,%yy%). Leave blank to use window coordinates (%x%`,%y%),,300, 140
	if inp =
		return
	if errorlevel
		return
	if inp=
		code =ControlClick,x%x% y%y%, %win%
	if inp = S
		code =Click, x%xx% y%yy%
}
if action = Control Click
	code = ControlClick, %contrl%, %win%
if action = Press Buttons Control
{
	InputBox, inp, Press Buttons Control, Type Buttons to press`, use `{`} to enclose real keys like `{Enter`} use `` to escape specials,,300, 140
	if inp =
		return
	if errorlevel
		return
	code =ControlSend, %contrl%, %inp%, %win%
}	
	
if action = Press Buttons
{
	InputBox, inp, Press Buttons, Type Buttons to press`, use `{`} to enclose real keys like `{Enter`} use `` to escape specials,,300, 140
	if inp =
		return
	if errorlevel
		return
	code =Send, %inp%
}
if action = ComboBox Choose
{
	InputBox, inp, ComboBox Choose, Type the Position of the Item to select on this,,300, 140
	if inp =
		return
	if errorlevel
		return
	code =Control, choose, %inp%, %contrl%, %win%
}
if action = ComboBox Choose Contains
{
	InputBox, inp,ComboBox Choose Contains, Type the name of the text to select in this control,,300, 140
	if inp =
		return
	if errorlevel
		return
	ControlGet, data, List,,%contrl%, %win%
	loop, parse, data, `n
		if a_loopfield contains %inp%
			code =Control, choose, %a_index%, %contrl%, %win%
}
if action = List Choose
{
	InputBox, inp, ComboBox Choose, Type the Position of the Item to select on this,,300, 140
	if inp =
		return
	if errorlevel
		return
	code =Control, choose, %inp%, %contrl%, %win%
}
if action = Sleep
{
	InputBox, inp, ComboBox Choose, Type milliseconds to sleep,,300, 140
	if inp =
		return
	if errorlevel
		return
	code = Sleep, %inp%
}
if action = WinWaitActive
{
	InputBox, inp, WinWait, Type the window to wait for. Leave blank to select this one,,300, 140
	if inp =
		return
	if errorlevel
		return
	if inp !=
		code =WinWaitActive, %inp%
	else
		code =WinWaitActive, %win%
}
if action = WinWaitClose
{
	InputBox, inp, WinWait, Type the window to wait for. Leave blank to select this one,,300, 140
	if inp =
		return
	if errorlevel
		return
	if inp !=
		code =WinWaitClose, %inp%
	else
		code =WinWaitClose, %win%
}
if action = WinWait
{
	InputBox, inp, WinWait, Type the window to wait for. Leave blank to select this one,,300, 140
	if inp =
		return
	if errorlevel
		return
	if inp !=
		code =WinWait, %inp%
	else
		code =WinWait, %win%
}
code = %code%
if code != 
	script .= (script = "" ? code : "`n" code)
return

save:
FileSelectFile, file, S,%a_mydocuments%,Save Script, AutoHotKey Awesome Script(*.ahk)
if errorlevel
	return
if file=
	return
script .= "`nExitApp"
FileAppend, %script%, %file%.ahk
MsgBox,262144,GScript, File Saved!
return

Preview:
Gui, 2: destroy
Gui, 2: +alwaysontop +toolwindow
Gui, 2: Add, Text, x2 y0 w1 h1 vtxt,
Gui, 2: Add, Edit, x2 y0 w450 h360, %script%
Gui, 2: Show, w454 h365, Preview
Gui, 2: Default
GuiControl, focus, txt
return